config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings
from places.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('places.urls', namespace='places')),
    path('accounts/', include('allauth.urls')),
    path('logout/', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

places/urls.py
from django.urls import path

from . import views


app_name = 'places'

urlpatterns = [
    path ('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('new/', views.CreatePlace.as_view(), name='create'),
    path('edit/<int:pk>', views.EditPlace.as_view(), name='edit'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.custom_logout, name='logout'),
]

places/models.py
from django.contrib.auth import get_user_model
from django.contrib.gis.db import models


class Place(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь', related_name='places'
    )
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    locations = models.PointField(verbose_name='Местоположение')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    class Meta:
        verbose_name = 'Место'
        verbose_name_plural = 'Места'
        ordering = ['-time_create']


    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

places/forms.py
from django import forms
from leaflet.forms.widgets import LeafletWidget

from .models import Place


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['title', 'comment', 'locations']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'locations': LeafletWidget(),
        }

places/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseNotFound
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView, UpdateView

from .forms import PlaceForm
from .models import Place


class IndexView(TemplateView):
    template_name = 'index.html'
    extra_context = {
        'title_page': 'Главная страница',
    }


class HomeView(LoginRequiredMixin, ListView):
    model = Place
    template_name = 'places/home.html'
    context_object_name = 'posts'
    title_page = 'Домашняя страница'

    def get_queryset(self):
        return Place.objects.filter(user=self.request.user).select_related('user')


class CreatePlace(LoginRequiredMixin, CreateView):
    model = Place
    form_class = PlaceForm
    template_name = 'places/add_place.html'
    extra_context = {
        'title_page': 'Добавить воспоминание',
    }
    success_url = reverse_lazy('places:home')

    def form_valid(self, form):
        place = form.save(commit=False)
        place.user = self.request.user
        place.save()
        return super().form_valid(form)


class EditPlace(LoginRequiredMixin, UpdateView):
    model = Place
    form_class = PlaceForm
    template_name = 'places/add_place.html'
    extra_context = {
        'title_page': 'Редактировать воспоминание',
    }
    success_url = reverse_lazy('places:home')


def page_not_found(request, exception):
    if isinstance(exception, Http404):
        return render(
            request,
            '404.html',
            {
                'title_page': 'Страница не найдена',
                'title': 'Страница не найдена',
                'message': 'К сожалению, мы не можем найти такую страницу.',
            },
        )

    return HttpResponseNotFound('<h1>Страница не найдена</h1>')

users/views.py
# Create your views here.
from allauth.account.views import logout
from django.shortcuts import redirect


def custom_logout(request):
    logout(request)
    return redirect('places:index')

places/templates/places/add_place.html
{% extends 'base.html' %}
{% load leaflet_tags %}

{% block title %} {{ title_page }} {% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h1 class="mb-4">{{ title_page }}</h1>
            </div>
            <div class="form-group">
                <form id="memory-form" method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div id="id_location_map" style="height: 400px;"></div>
                    
                    <div class="form-group mt-4"> <button type="submit" class="btn btn-primary">Сохранить</button> </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var map = L.map('id_location_map');

        // Определение слоя карты (например, OpenStreetMap)
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; OpenStreetMap contributors'
        }).addTo(map);

        // Центрирование карты и установка начального зума
        map.setView([56.002778, 92.854167], 12);

        // Переменная для хранения метки
        var marker;

        // Добавление обработчика кликов по карте
        map.on('click', function(e) {
            // Удаление старой метки, если она существует
            if (marker) {
                map.removeLayer(marker);
            }

            // Добавление новой метки в место клика
            marker = L.marker(e.latlng).addTo(map);

            // Обновление значения поля формы
            document.getElementById('id_locations').value = "POINT(" + e.latlng.lng + " " + e.latlng.lat + ")";
        });
    });
</script>
{% endblock %}

places/templates/places/home.html
{% extends 'base.html' %}
{% load leaflet_tags %}

{% block title %} {{ title_page }} {% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h1 class="mb-0">Воспоминания</h1>
                <a href="{% url 'places:create' %}" class="btn btn-outline-success">Добавить воспоминание</a>
            </div>

            {% if posts %}
            {% for post in posts %}
            <div class="card bg-light mb-3">
                <div class="card-header">{{ post.title }}</div>
                <div class="card-body">
                    <p class="card-text">{{ post.comment }}</p>
                    <div id="map-{{ post.id }}" style="height: 300px ; width: 100% ;"></div>
                    <script>
                        document.addEventListener("DOMContentLoaded", function() {
                            // Извлечение координат из post.locations
                            var coordinates = "{{ post.locations }}".match(/POINT \(([^)]+)\)/)[1].split(" ");
                            var lon = parseFloat(coordinates[0]);
                            var lat = parseFloat(coordinates[1]);

                            var map = L.map('map-{{ post.id }}').setView([lat, lon], 13);

                            // Определение слоя карты (например, OpenStreetMap)
                            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                                attribution: '&copy; OpenStreetMap contributors'
                            }).addTo(map);

                            // Добавление метки на карту
                            var marker = L.marker([lat, lon]).addTo(map);
                        });
                    </script>
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                          <a href="{% url 'places:edit' post.id %}" class="btn btn-sm btn-outline-secondary me-2 mt-4">Редактировать</a>
                        </li>
                    </ul>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="alert alert-info" role="alert">
                У вас нет ни одного воспоминания
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
{% load leaflet_tags %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    {{ leaflet_css }}
    {{ leaflet_js }}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %} 
        {% endblock %}
    </title>
    <link type="text/css" href="{% static 'places/css/styles.css' %}" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Подключение Leaflet -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <style>
      body {
        padding-top: 56px; /* Высота навигационной панели */
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <div class="container">
          <a class="navbar-brand" href="{% url 'places:home' %}">PLACES REMEMBER</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ms-auto">
                  {% if user.is_authenticated %}
                  <li class="nav-item me-2">
                    <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="Profile Picture" class="rounded-circle" style="width: 40px; height: 40px; object-fit: cover;">
                    </li>
                    <li class="nav-item align-items-center d-flex">
                        <span class="navbar-text me-2">{{ user.username }}</span>
                    </li>
                    <li class="nav-item ms-2">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                  {% else %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'account_login' %}">Войти</a>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </div>
  </nav>
  <div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <div class="row">
              <div class="col">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
                    </div>
                  {% endfor %}
                {% endif %}
              </div>
            </div>
        </div>
    </div>
  </div>
    {% block content %} {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block content %}
<div class="container text-center my-5">
    <h1 class="display-5">
        Добро пожаловать на "Places Remember"!
    </h1>
    <p class="lead text-muted">
        Это приложение позволяет сохранять и делиться впечатлениями от посещенных мест. Вы можете создавать записи о своих потрясающих путешествиях, которые будут доступны только вам.
    </p>
    <div class="row justify-content-center my-5 align-items-stretch">
        <div class="col-12 col-md-3">
            <div class="card rounded bg-light shadow h-100">
                <div class="card-body d-flex flex-column justify-content-center">
                    <h4 class="card-title text-dark text-center mb-4">Пожалуйста, войдите, чтобы начать.</h4>
                    <div class="d-grid gap-3">
                        <a href="{% provider_login_url 'github' %}" class="btn btn-outline-dark">
                            <i class="fa fa-github fa-fw"></i>
                            <span>Login with GitHub</span>
                        </a>
                        <a href="{% provider_login_url 'vk' %}" class="btn btn-outline-dark">
                            <i class="fa fa-vk fa-fw"></i>
                            <span>Войти через ВКонтакте</span>
                        </a>
                        <a href="{% provider_login_url 'mailru' %}" class="btn btn-outline-dark">
                            <i class="fa fa-envelope-o fa-fw"></i>
                            <span>Войти через Mail.Ru</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-9">
          <div id="carouselExampleIndicators" class="carousel rounded slide carousel-dark shadow fixed-carousel" data-bs-ride="carousel" data-bs-interval="3000">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'places/images/1.png' %}" class="d-block w-100 fixed-carousel-img" alt="Post 1 Image">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'places/images/2.png' %}" class="d-block w-100 fixed-carousel-img" alt="Post 2 Image">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'places/images/3.png' %}" class="d-block w-100 fixed-carousel-img" alt="Post 3 Image">
                    <div class="carousel-caption d-none d-md-block">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}